version: 2
registries:
  maven-repository-leiainc-jfrog-io-leiainc-gradle-dev:
    type: maven-repository
    url: https://leiainc.jfrog.io/leiainc/gradle-dev
    username: leiaprivate
    password: "${{secrets.MAVEN_REPOSITORY_LEIAINC_JFROG_IO_LEIAINC_GRADLE_DEV_PASSWORD}}"
  maven-repository-leiainc-jfrog-io-leiainc-maven-dev-local:
    type: maven-repository
    url: https://leiainc.jfrog.io/leiainc/maven-dev-local
    username: leiaprivate
    password: "${{secrets.MAVEN_REPOSITORY_LEIAINC_JFROG_IO_LEIAINC_MAVEN_DEV_LOCAL_PASSWORD}}"

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.3.0
    - 1.3.1
    - 1.3.2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.google.android.exoplayer:exoplayer
    versions:
    - 2.13.0
    - 2.13.1
    - 2.13.2
  - dependency-name: androidx.lifecycle:lifecycle-runtime-ktx
    versions:
    - 2.3.0
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.3.0
  registries:
  - maven-repository-leiainc-jfrog-io-leiainc-gradle-dev
  - maven-repository-leiainc-jfrog-io-leiainc-maven-dev-local
